import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import fs from "fs/promises";
import path from "path";
import { EazyWordsDialog, OpenModalButton, WordCountCard } from "../components";
import { useStore } from "../store";
import type { Match, WordFilter } from "../types/index";

const PARAGRAPH = `My uncle Mike is a music teacher. He never gets up very late. He usually gets up at five o’clock in the morning. After he brushes his teeth, he often plays baseball with my aunt. Then he eats breakfast. After that, he often plays the violin. At about seven fifty he takes the No. 6 bus to school. 
He has no classes on Thursday and Friday. He usually goes to the violin club. There he helps kids with the violin. Oh, my brother plays the violin very well. Do you love to play the violin? Do you want to join the violin club? Please call my uncle at 116-3886.`;

type TextData = {
  data: string[];
};

type Props = {
  primaryData: TextData;
  juniorData: TextData;
  seniorData: TextData;
  easyData: TextData;
  primaryDataSplited: {
    title: string;
    content: string[];
  }[];
};

const Home: NextPage<Props> = ({
  primaryData,
  juniorData,
  seniorData,
  easyData,
  primaryDataSplited,
  ...props
}) => {
  const [paragraph, setParagraph] = useState(PARAGRAPH);
  console.log(props);
  return (
    <>
      <Head>
        <title>段落单词分析APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center space-y-2 p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          段落单词 <span className="text-purple-300">分析</span> App
        </h1>
        <OpenModalButton />
        {/* <div>
          <input type="checkbox" checked={} />
        </div> */}
        <EazyWordsDialog easyWords={easyData.data} />
        <section className="flex w-full space-x-2">
          <textarea
            placeholder={paragraph}
            value={paragraph}
            onChange={(e) => setParagraph(e.target.value)}
            className="no-scrollbar resize-none overflow-y-scroll rounded border border-red-300 bg-red-50 p-3 text-slate-400 focus:outline-none"
          ></textarea>
          <div className="flex flex-1 space-x-2">
            <WordCountCard
              title="小学"
              data={primaryData.data}
              paragraph={paragraph}
              splitedData={primaryDataSplited}
            />
            <WordCountCard
              title="初中"
              data={juniorData.data}
              paragraph={paragraph}
            />
            <WordCountCard
              title="高中"
              data={seniorData.data}
              paragraph={paragraph}
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;

const dataSources = [
  "src/data/简单.json",
  "src/data/小学.json",
  "src/data/初中.json",
  "src/data/高中.json",
  "src/data/小学一上.json",
  "src/data/小学一下.json",
  "src/data/小学二上.json",
  "src/data/小学二下.json",
  "src/data/小学三上.json",
  "src/data/小学三下.json",
  "src/data/小学四上.json",
  "src/data/小学四下.json",
  "src/data/小学五上.json",
  "src/data/小学五下.json",
  "src/data/小学六上.json",
  "src/data/小学六下.json",
];

export const getStaticProps: GetStaticProps<Props> = async () => {
  const [
    easyData,
    primaryData,
    juniorData,
    seniorData,
    gradeOneFirstData,
    gradeOneSecondData,
    gradeTwoFirstData,
    gradeTwoSecondData,
    gradeThreeFirstData,
    gradeThreeSecondData,
    gradeFourFirstData,
    gradeFourSecondData,
    gradeFiveFirstData,
    gradeFiveSecondData,
    gradeSixFirstData,
    gradeSixSecondData,
  ] = await Promise.all(
    dataSources.map((source) =>
      fs.readFile(path.resolve(process.cwd(), source), {
        encoding: "utf8",
      })
    )
  ).then((d) => d.map((s) => JSON.parse(s)));

  return {
    props: {
      primaryData,
      juniorData,
      seniorData,
      easyData,
      primaryDataSplited: [
        { title: "小学一上", content: gradeOneFirstData },
        { title: "小学一下", content: gradeOneSecondData },
        { title: "小学二上", content: gradeTwoFirstData },
        { title: "小学二下", content: gradeTwoSecondData },
        { title: "小学三上", content: gradeThreeFirstData },
        { title: "小学三下", content: gradeThreeSecondData },
        { title: "小学四上", content: gradeFourFirstData },
        { title: "小学四下", content: gradeFourSecondData },
        { title: "小学五上", content: gradeFiveFirstData },
        { title: "小学五下", content: gradeFiveSecondData },
        { title: "小学六上", content: gradeSixFirstData },
        { title: "小学六下", content: gradeSixSecondData },
      ],
    },
  };
};
